# Data Inconsistencies

####  Inconsistent Format

- dd-mm-yy
- yyyy-mm-dd
- dd/mm/yy
- 19th May 2019

### Inconsistent Naming Convertion

- US 
- United States
- United States of America
- USA
- America

### Typographic errors

- pakistan
- paakistan
- Pakistaan
- PakstaN

### Duplication

- Duplicated data of same id 
- Same data entered multiple times, sometimes with slight variations.

### Contradictory


- A person's age is listed as 25 in one record and 32 in another.

- One row says "Gender: Male", another says "Gender: Female" for the same ID
- Age of a son is above than his father

In [13]:
# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [14]:
# Data having Inoconsistent Data Types

data={'date':['2021-12-01','12-02-2021','2021/12/03','2021.12.04'],
      'Country':['USA','America','US','United States'],
      'Name':['john Doe','Jane','john doe','Jane Doe'],
      'sales':[100,200,200,None],
      'sales2':[100.0,200.0,300.0,None]}
df=pd.DataFrame(data)

In [15]:
df.head()

         date        Country      Name  sales  sales2
0  2021-12-01            USA  john Doe  100.0   100.0
1  12-02-2021        America      Jane  200.0   200.0
2  2021/12/03             US  john doe  200.0   300.0
3  2021.12.04  United States  Jane Doe    NaN     NaN

In [16]:
# Convert date column to datetime
df['date'] = pd.to_datetime(df['date'], errors='coerce')
df['date'] = df['date'].dt.strftime('%Y-%m-%d')
df.head()

         date        Country      Name  sales  sales2
0  2021-12-01            USA  john Doe  100.0   100.0
1         NaN        America      Jane  200.0   200.0
2         NaN             US  john doe  200.0   300.0
3         NaN  United States  Jane Doe    NaN     NaN

In [17]:
 # Replace the NaN value in the date columns with the date of the first row
 
df['date'].fillna(df['date'].iloc[0], inplace=True)
# Convert the date column to datetime format
df['date'] = pd.to_datetime(df['date'], format='%Y-%m-%d')
df['date'] = df['date'].dt.strftime('%Y-%m-%d')
df.head()

C:\Users\dell\AppData\Local\Temp\ipykernel_13200\2274384375.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['date'].fillna(df['date'].iloc[0], inplace=True)

         date        Country      Name  sales  sales2
0  2021-12-01            USA  john Doe  100.0   100.0
1  2021-12-01        America      Jane  200.0   200.0
2  2021-12-01             US  john doe  200.0   300.0
3  2021-12-01  United States  Jane Doe    NaN     NaN

In [18]:
# Harmonize the country names
country_mapping = {
    'USA': 'United States',
    'America': 'United States',
    'US': 'United States',
    'United States': 'United States'
}

df['Country'] = df['Country'].replace(country_mapping)
df['Country'] = df['Country'].str.title()
df.head()

         date        Country      Name  sales  sales2
0  2021-12-01  United States  john Doe  100.0   100.0
1  2021-12-01  United States      Jane  200.0   200.0
2  2021-12-01  United States  john doe  200.0   300.0
3  2021-12-01  United States  Jane Doe    NaN     NaN

In [21]:
# Correct the typo graphical mistakes in the Name column
name_mapping = {
    'john Doe': 'John Doe',
    'Jane': 'Jane Doe',
    'john doe': 'John Doe',
    'Johne Doe': 'Jane Doe'
}
df['Name'] = df['Name'].replace(name_mapping)
df.head()

         date        Country      Name  sales  sales2
0  2021-12-01  United States  John Doe  100.0   100.0
1  2021-12-01  United States  Jane Doe  200.0   200.0
2  2021-12-01  United States  John Doe  200.0   300.0
3  2021-12-01  United States  John Doe    NaN     NaN

In [22]:
# Remove duplicates
df=df.drop_duplicates(subset=['date','Country','Name'])
df.head()

         date        Country      Name  sales  sales2
0  2021-12-01  United States  John Doe  100.0   100.0
1  2021-12-01  United States  Jane Doe  200.0   200.0

In [23]:
# Resolving Contridatory Data problems
# sales first column is always greater than sales2 column
df=df.drop(df[df['sales']<=df['sales2']].index)
df.head()

Empty DataFrame
Columns: [date, Country, Name, sales, sales2]
Index: []